export const STRUCTURE_CREATE_APARTMENT_REQUEST =
  "STRUCTURE_CREATE_APARTMENT_REQUEST";
export const STRUCTURE_CREATE_APARTMENT_SUCCESS =
  "STRUCTURE_CREATE_APARTMENT_SUCCESS";
export const STRUCTURE_CREATE_APARTMENT_FAIL =
  "STRUCTURE_CREATE_APARTMENT_FAIL";
