export const USER_CREATE_APARTMENT_REQUEST = "USER_CREATE_APARTMENT_REQUEST";
export const USER_CREATE_APARTMENT_SUCCESS = "USER_CREATE_APARTMENT_SUCCESS";
export const USER_CREATE_APARTMENT_FAIL = "USER_CREATE_APARTMENT_FAIL";
