export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_CREATE_ADMIN_REQUEST = "USER_CREATE_ADMIN_REQUEST";
export const USER_CREATE_ADMIN_SUCCESS = "USER_CREATE_ADMIN_SUCCESS";
export const USER_CREATE_ADMIN_FAIL = "USER_CREATE_ADMIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
