export const USER_CREATE_COMPLAINTS_REQUEST = "USER_CREATE_COMPLAINTS_REQUEST";
export const USER_CREATE_COMPLAINTS_SUCCESS = " USER_CREATE_COMPLAINTS_SUCCESS";
export const USER_CREATE_COMPLAINTS_FAIL = "USER_CREATE_COMPLAINTS_FAIL";
